### ISSUE TITLE
Always retrieve 'language', 'script', and 'region' options

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-locale#18]
The 'language', 'script', and 'region' options should always be retrieved and validated, even when unused, for consistency with Unicode extension options and for consistency with other Intl constructors, e.g. compare to `InitializeNumberFormat` which gets and validates the `currency` and `currencyDisplay` options even when `style` is not `"currency"`.

**Comment by littledan** [comment]
In particular, even when not matching the `langtag` production? I'd be OK with this change.
