### ISSUE TITLE
transfer ownership

### ISSUE THREAD

**Issue by zbraniecki** [tc39/proposal-intl-locale#5]
@bterlson can you accept the transfer pls?

**Comment by bterlson** [comment]
It expires after a few hours if you sent one already. But there's a new process that @ljharb can hook you up with while I'm mobile.

**Comment by zbraniecki** [comment]
ok. I refreshed the transfer in case you get online :)

**Comment by ljharb** [comment]
You should be an admin on the TC39-transfer org - can you transfer the repo there? That will be immediate, and then @bterlson can pull it into the TC39 org.

**Comment by zbraniecki** [comment]
@ljharb - I got `You don’t have the permission to create repositories on tc39-transfer ` error when tried.

**Comment by ljharb** [comment]
@zbraniecki whoops, fixed! you're now invited to the org

**Comment by zbraniecki** [comment]
done! thanks. :)

**Comment by ljharb** [comment]
@bterlson please feel free to transfer this repo into the tc39 org at your leisure :-)

**Comment by bterlson** [comment]
All done. This new process is awesome.
