### ISSUE TITLE
InsertUnicodeExtension when called from ApplyUnicodeExtensionToTag cannot fail

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-locale#56]
ApplyUnicodeExtensionToTag, step 10.a
> 10. If newExtension is not the empty String, then
>     a. Let locale be ? InsertUnicodeExtension(locale, newExtension).

But InsertUnicodeExtension can only fail when `locale` is either a grandfathered or private-use only tag, see InsertUnicodeExtension, step 3.
> 3. If locale matches the privateuse or the grandfathered production, throw a RangeError exception.

And when called from ApplyUnicodeExtensionToTag, `locale` is never a grandfathered or private-use only tag, because of ApplyUnicodeExtensionToTag, step 2.
> 2. If tag matches the privateuse or the grandfathered production, then
>   ...
>   d. Return result.

**Comment by littledan** [comment]
Fixed by https://github.com/tc39/proposal-intl-locale/pull/66
